# Generated by Django 5.2.3 on 2025-06-14 16:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('applicable_days', models.JSONField(help_text="List of days (e.g., ['Mon', 'Tue'])")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DistanceBasePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('up_to_km', models.FloatField()),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distance_base_prices', to='pricing.pricingconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='DistanceAdditionalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('starts_after_km', models.FloatField()),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distance_additional_prices', to='pricing.pricingconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.pricingconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='TimeMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_minute', models.PositiveIntegerField(help_text='Start time in minutes (e.g., 60 for 1 hour)')),
                ('to_minute', models.PositiveIntegerField(help_text='End time in minutes (e.g., 120 for 2 hours)')),
                ('multiplier', models.FloatField()),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_multipliers', to='pricing.pricingconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='WaitingCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_wait_minutes', models.PositiveIntegerField(default=3)),
                ('charge_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_duration_minutes', models.PositiveIntegerField(default=3)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_charges', to='pricing.pricingconfiguration')),
            ],
        ),
    ]
